# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"comte": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://EtienneDavid.github.io/package_detection/"

git_url = "https://github.com/EtienneDavid/package_detection/tree/master/"

def custom_doc_links(name): return None
